CREATE TABLE IF NOT EXISTS USER (
    ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME varchar(50) NOT NULL UNIQUE,
    PASSWORD varchar(250) NOT NULL,
    ROLE varchar(50) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
