CREATE TABLE IF NOT EXISTS AUTHOR (
    ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME varchar(50),
    EMAIL varchar(50),
    PHONE_NUMBER varchar(50),
    ADDRESS varchar(250),
    INFORMATION varchar(250)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS BOOK (
    ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME varchar(50),
    DESCRIPTION varchar(250)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS BOOK_AUTHOR (
    BOOK_ID bigint NOT NULL,
    AUTHOR_ID bigint NOT NULL,
    PRIMARY KEY (BOOK_ID, AUTHOR_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE BOOK_AUTHOR
ADD CONSTRAINT BOOK_AUTHOR_AUTHOR_ID_FK
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR;

ALTER TABLE BOOK_AUTHOR
ADD CONSTRAINT BOOK_AUTHOR_BOOK_ID_FK
FOREIGN KEY (BOOK_ID) REFERENCES BOOK;
